version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - redmine_network
    environment:
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}

  redmine:
    image: docker.io/bitnami/redmine:4
    ports:
      - '3001:3000'
    networks:
      - redmine_network
      - traefik-external
    volumes:
      - 'redmine_data:/bitnami/redmine'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-external"
      - "traefik.port=3000"
    depends_on:
      - mariadb
    environment:
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=${DB_USER}
      - REDMINE_DATABASE_PASSWORD=${DB_USER_PASSWORD}
      - REDMINE_DATABASE_NAME=${DB_NAME}
      - REDMINE_USERNAME=${ADMIN_USERNAME}
      - REDMINE_PASSWORD=${ADMIN_PASSWORD}
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

networks:
  redmine_network:
  traefik-external:
    external: true